module.exports = {
  extractText: /^\d+\..*?(?=\r\n\r\n)/gms,
  type1: /^[A-Z]\).*\*$/m,
  type2: /^(true|false)$/im,
  type3: /(^[A-Z]\)\s*.*?\s*\*\s*){2,}$/gms,
  fillTheBlanksType: /_+/,
  matchItType: /^[A-Z]\).*\s*:\s*.+$/m,
  clozeType: /---.*---/m,
  errorCorrectionType: /^\d\).*$/m,
  descriptiveType: /^\(\d+\).* words$/m,
  questionWithMarks: /(?<=\d+\.\s*)(.*?)(?=\(\s*\d+,\s*-\d+\))/,
  questionWithoutMarks: /(?<=\d+\.\s*)(.*?)\(\d+\)/s,
  questionWithOptions: /(?<=\d+\.\s*)(.*?)(?=\r\n[A-Z]\))/s,
  errorCorrectionQuestion: /(?<=\d+\.\s*)(.*?)(?=\r\n\d\))/s,
  descriptiveQuestion: /(?<=\d+\.\s*)(.*?)(?=\r\n\(\d+\) word)s/s,
  type2Question: /(?<=\d+\.\s*).*?(?=\r\ntrue|\r\nfalse|$)/s,
  point: /(?<=\()(\d+)(?=,?(?:\s*-?\d+)?\)\r\n|$)/s,
  mpoint: /(?<=\(\d+,\s*)(-\d+)(?=\)\r\n|$)/s,
  options: /(?<=[A-Z]\)\s*)(.*?)(?=\*?\r\n|$)/gs,
  explanation: /(?<=\n--\s)(.*?)(?=\r\n\r\n|$)/gms,
  type1Answer: /[A-Z\d]\)\s*(.*?)\*/,
  type3Answer: /(?<=[A-Z]\)\s*)(.*?)(?!\r\n)(?=\*)/g,
  otherAnswers: /(?<=\n[A-Z\d]\)\s*)(.*?)(?=\r\n|$)/gs,
  matchItAnswer: /^[A-Z\d]\)\s*(.*)\s*:\s*(.*?)(?=\r\n|$)/gms,
  matchIt1Answer: /(?<=[A-Z]\)\s*)(.*?)(?=:)/gs,
  matchIt2Answer: /(?<=:\s*)(.*?)(?=\r\n|$)/gs,
  type2Answer: /^(true|false)$/im,

}